create table SvRegisterSpk (
	CompanyCode varchar(15) NOT NULL,
	BranchCode varchar(15) NOT NULL,
	ProductType varchar(15) NOT NULL,
	ServiceNo bigint NOT NULL,
	TaskPartNo varchar(50) NOT NULL,
	TaskPartSeq numeric(4, 0) NOT NULL,
	JobOrderNo varchar(15) NULL,
	JobOrderDate datetime NULL,
	BasicModel varchar(15) NULL,
	PoliceRegNo varchar(15) NULL,
	Odometer numeric(10, 0) NULL,
	CustomerCode varchar(15) NULL,
	CustomerName varchar(100) NULL,
	GroupJobType varchar(15) NULL,
	GroupJobTypeDesc varchar(100) NULL,
	JobType varchar(15) NOT NULL,
	JobTypeDesc varchar(100) NULL,
	OperationNo varchar(50) NULL,
	OperationName varchar(100) NULL,
	OperationHour numeric(7, 2) NULL,
	FmID varchar(15) NULL,
	FmName varchar(100) NULL,
	SaID varchar(15) NULL,
	SaName varchar(100) NULL,
	MechanicID varchar(15) NOT NULL,
	MechanicName varchar(100) NULL,
	PartNo varchar(20) NULL,
	PartName varchar(100) NULL,
	DemandQty numeric(12, 2) NULL,
	SupplyQty numeric(12, 2) NULL,
	ReturnQty numeric(12, 2) NULL,
	SupplySlipNo varchar(15) NULL,
	SSReturnNo varchar(15) NULL,
	TaskPartType varchar(1) NOT NULL,
	ServiceRequestDesc varchar(max) NULL,
	ServiceStatus char(1) NULL,
	ServiceStatusDesc varchar(19) NULL,
	TotalSrvAmount numeric(18, 0) NULL,
	InvoiceNo varchar(15) NULL,
	CreatedBy varchar(15) NULL,
	CreatedDate datetime NULL,
	LastUpdateBy varchar(15) NULL,
	LastUpdateDate datetime NULL,
	primary key clustered 
	(
		CompanyCode,
		BranchCode,
		ProductType,
		ServiceNo,
		TaskPartNo,
		TaskPartSeq
	)
) 



