insert into SysDataType (DataType, DataTypeDesc)
values ('CSBDAY', 'CSBDAY - Customer Birthday')
      , ('CSBKPB', 'CSBKPB - Customer BPKB')
      , ('CSCUSTDATA', 'CSCUSTDATA - Customer Data')
      , ('CSFEEDBACK', 'CSFEEDBACK - Customer Feedback')
      , ('CSHLDAY', 'CSHLDAY - Customer Holiday')
      , ('CSVHCL', 'CSVHCL - Customer Vehicle')
      , ('CSRLTN', 'CSRLTN - Customer Relation')
      , ('CSMSTHLDAY', 'CSMSTHLDAY - Master Holiday for Customer')
      , ('CSSTNKEXT', 'CSSTNKEXT - STNK Extension')
      , ('CS3DCALL', 'CS3DCALL - 3 Days Call')
      , ('TRSLSINVIN', 'TRSLSINVIN - Sales Invoice Vin')
      , ('TRSLSINV', 'TRSLSINV - Sales Invoice')
      , ('MSTCUST', 'MSTCUST - Master Customer')
      , ('TRSLSDODTL', 'TRSLSDODTL - Sales DO Detail')
      , ('TRSLSDO', 'TRSLSDO - Sales DO')
      , ('SVMSTCVHCL', 'SVMSTCVHCL - Master Vehicle')
      , ('TRSLSBPK', 'TRSLSBPK - Sales BPK')
      , ('TRSLSSO', 'TRSLSSO - Sales SO')
   