require.config({

    baseUrl: "../../",
    waitSeconds: 0,
    // alias libraries paths
    paths: {

        'jquery': 'content/scripts/libs/jquery/jquery-2.1.4.min',
        'jquery-ui': 'content/scripts/libs/jquery/jquery-ui.min',
        'bootstrap': 'content/scripts/libs/bootstrap/bootstrap.min',        
        'modernizr': 'Content/scripts/libs/modernizr-2.8.3.min',
        'underscore': 'Content/scripts/libs/underscore-min',
        'moment': 'Content/scripts/libs/moment/moment.min',
        'jquery-layout': 'Content/Scripts/libs/jquery/jquery.layout.min',
        'toastr': 'Content/Scripts/libs/angular-ui/toastr.min',
        'bootbox': 'Content/Scripts/libs/angular-ui/bootbox.min',
        'q': 'Content/Scripts/libs/angular-ui/q.min',
        'underscore': 'Content/Scripts/libs/underscore.min',

        'core': 'content/scripts/core',
        'codemirror': 'content/scripts/codemirror',

        'angular': 'content/scripts/libs/angular/angular.min',
        'angular-cookies': 'content/scripts/libs/angular/angular-cookies.min',
        'angular-resource': 'content/scripts/libs/angular/angular-resource.min',
        'angular-sanitize': 'content/scripts/libs/angular/angular-sanitize.min',
        'angular-animate': 'content/scripts/libs/angular/angular-animate.min',
        'angular-route': 'content/scripts/libs/angular/angular-route.min',

        'ui-router': 'content/scripts/libs/angular-ui/angular-ui-router.min',
        'ui-google-maps': 'content/scripts/libs/angular-ui/angular-google-maps.min',
        'ui-bootstrap': 'content/scripts/libs/angular-ui/ui-bootstrap-tpls-0.12.1.min',
        'angular-markdown-text': 'content/scripts/libs/angular-ui/angular-markdown-text.min',
         
        'angular-formly': 'content/scripts/libs/angular-ui/formly.min',
        'kendo': 'content/scripts/libs/kendo/kendo.all.min',
        'angular-formly-bootstrap': 'content/scripts/libs/angular-ui/angular-formly-templates-bootstrap.min',
        'ui-codemirror': 'content/scripts/libs/angular-ui/ui-codemirror',
        'ui-select': 'content/scripts/libs/angular-ui/select.min',
        'ngNotify': 'content/scripts/libs/angular-ui/ng-notify.min',
        'autofocus': 'content/scripts/libs/angular-ui/autofocus.min',
        'angular-block-ui': 'content/scripts/libs/angular-ui/angular-block-ui.min',
        'bootbox': 'content/scripts/libs/angular-ui/bootbox.min',
        'ngDialog': 'content/scripts/libs/angular-ui/ngdialog.min',
        'ui-utils': 'content/scripts/libs/angular-ui/ui-utils.min',
        'ui-utils-ieshiv': 'content/scripts/libs/angular-ui/ui-utils-ieshiv.min',
        'dialogs': 'content/scripts/libs/angular-ui/dialogs.min',
        'dialogs-tpl': 'content/scripts/libs/angular-ui/dialogs-default-translations.min',
        'ngTranslate': 'content/scripts/libs/angular-ui/angular-translate.min',

        'pickDay': 'content/scripts/libs/grid/handsontable/plugins/pikaday.min',
        'hand-select2': 'content/scripts/libs/grid/handsontable/plugins/select2-editor.min',
        'ZeroClipboard': 'content/scripts/libs/grid/handsontable/plugins/ZeroClipboard.min',
        'handsontable': 'content/scripts/libs/grid/handsontable/handsontable.full.min',
        'ngHandsontable': 'content/scripts/libs/angular-ui/nghandsontable.min',
        'ngRule': 'content/scripts/libs/grid/handsontable/plugins/ruleJS.all.full.MIN',
        'ngFormula': 'content/scripts/libs/grid/handsontable/plugins/handsontable.formula.MIN',

        'bootstrap-decorator': 'content/scripts/libs/angular-ui/bootstrap-decorator.min',
        'schemaForm': 'content/scripts/libs/angular-ui/schema-form',
        'sortable': 'content/scripts/libs/angular-ui/sortable.min',
        'colorpicker': 'content/scripts/libs/angular-ui/angular-spectrum-colorpicker.min',
        'angular-underscore': 'content/scripts/libs/angular-ui/angular-underscore.min',
        'autofields': 'content/scripts/libs/angular-ui/autofields.min',
        'autofields-bootstrap': 'content/scripts/libs/angular-ui/autofields-bootstrap.min',
        'door3css': 'content/scripts/libs/angular-ui/angular-css.min',
        'adapt-strap': 'content/scripts/libs/angular-ui/adapt-strap.min',
        'adapt-strap.tpl': 'content/scripts/libs/angular-ui/adapt-strap.tpl.min',
        'toastr': 'content/scripts/libs/angular-ui/toastr.min',
        'xtform': 'content/scripts/libs/angular-ui/xtform.tpl',
        'ng-idle': 'content/scripts/libs/angular-ui/angular-idle.min',
        'ng-datatable': 'content/scripts/libs/angular-ui/angular-datatables.min',
        'amplify': 'content/scripts/libs/amplify.min',
        'ng-moment': 'content/scripts/libs/angular-ui/angular-moment.min',
        'ngMap': 'content/scripts/libs/angular-ui/ng-Map.min',
        'logToServer': 'content/scripts/libs/angular-ui/angular-logToServer.min',
        'angularModalService': 'content/scripts/libs/angular-ui/angular-modal-service.min',        
        'prettify': 'content/scripts/libs/prettify/prettify.min', 
        'async': 'content/scripts/libs/angular-ui/async.min',
        'objpath': 'content/scripts/libs/angular-ui/objectpath.min',
        'tv4': 'content/scripts/libs/angular-ui/tv4.min',
        'angularAMD': 'content/scripts/libs/angular-ui/angularAMD.min',
        'ngload': 'content/scripts/libs/angular-ui/ngload.min',
        'domReady': 'content/scripts/libs/domready.min',
        'api-check': 'content/scripts/libs/jquery/apicheck.min',
        'angular-form-gen': 'content/scripts/libs/angular-ui/angular-form-gen.min',
        'showdown': 'content/scripts/libs/angular-ui/showdown.min',
        'ng-bs3-datepicker': 'content/scripts/libs/angular-ui/ng-bs3-datepicker.min',
        'ng-wm': 'content/scripts/libs/angular-ui/angular-window-manager.min',
        'fullcalendar': 'content/scripts/libs/fullcalendar/dist/fullcalendar.min',
        'ng-calendar': 'content/scripts/libs/angular-ui-calendar/src/calendar',
        'scrollbars': 'content/scripts/libs/angular-ui/scrollbars.min',
        'dt-plugins': 'scripts/datatables-plugins',
        

        //         'app': 'api/files/templates/app/js',
        //'myapp': 'app'
    },

    // Add angular modules that does not support AMD out of the box, put it in a shim
    shim: {
        'angular': { 'exports': 'angular' },
        'angularAMD': ['angular'],
        'angular-route': ['angular'],
        'angular-route': ['angular'],
        'angular-resource': ['angular'],
        'angular-sanitize': ['angular'],
        'angular-animate': ['angular'],
        'ui-router': ['angular'],
        'ui-bootstrap': ['angular'],
        'ui-google-maps': ['angular', 'ui-bootstrap'],
        'angular-formly': ['angular', 'api-check'],
        'angular-formly-bootstrap': ['angular', 'angular-formly', 'api-check'],
        'kendo': ['angular', 'angular-animate'],
        //'kendo-ext': ['angular', 'angular-animate','kendo'],
        'ui-codemirror': ['angular', 'angular-animate'],
        'ui-select': ['angular', 'angular-animate', 'angular-sanitize'],
        'ngNotify': ['angular', 'angular-animate', 'ui-bootstrap'],
        'autofocus': ['angular', 'angular-animate'],
        'angular-block-ui': ['angular', 'angular-animate'],
        'ngDialog': ['angular', 'angular-animate', 'ui-bootstrap'],
        'dialogs': ['angular', 'angular-animate', 'ngTranslate', 'ui-bootstrap'],
        'dialogs-tpl': ['angular', 'angular-animate', 'ngTranslate', 'ui-bootstrap'],
        'ui-utils': ['angular', 'angular-animate'],
        'ui-utils-ieshiv': ['angular', 'angular-animate'],

        'pickDay': ['moment'],
        'handsontable': ['pickDay', 'ZeroClipboard', 'moment','kendo'],
        'ngRule': ['handsontable', 'kendo'],
        'hand-select2': ['handsontable', 'kendo'],
        'ngFormula': ['handsontable', 'ngRule', 'pickDay', 'kendo'],
        'ngHandsontable': ['angular', 'angular-animate','handsontable','ngRule','ngFormula','pickDay'],
        
        'ngTranslate': ['angular', 'angular-animate'],
        'sortable': ['angular', 'angular-animate', 'angular-sanitize', 'ui-bootstrap'],
        'colorpicker': ['angular', 'angular-animate', 'angular-sanitize', 'ui-bootstrap'],
        'angular-underscore': ['angular'],
        'schemaForm': ['angular', 'angular-animate', 'angular-sanitize', 'ui-bootstrap', 'sortable', 'colorpicker','objpath','tv4'],
        'bootstrap-decorator': ['angular', 'angular-animate', 'angular-sanitize', 'ui-bootstrap', 'schemaForm'],
        'autofields': ['angular', 'angular-animate', 'angular-sanitize'],
        'autofields-bootstrap': ['angular', 'angular-animate', 'angular-sanitize', 'ui-bootstrap', 'autofields'],
        'door3css': ['angular'],
        'adapt-strap': ['angular', 'angular-sanitize'],
        'adapt-strap.tpl': ['angular', 'angular-sanitize', 'adapt-strap'],
        'xtform': ['angular'],
        'ng-datatable': ['angular'],
        'dt-plugins': ['angular','ng-datatable'],
        'ng-idle': ['angular'],
        'ng-moment': ['angular'],
        'ngMap': ['angular'],
        'logToServer': ['angular'],
        'angularModalService': ['angular'],
        'angular-form-gen': ['angular', 'angular-sanitize', 'angular-animate'],
        'showdown': ['angular', 'angular-sanitize'],
        'angular-markdown-text': ['angular', 'angular-sanitize', 'showdown'],
        'ng-bs3-datepicker': ['angular', 'ui-bootstrap'],
        'ng-wm': ['angular', 'ui-bootstrap', 'angular-animate'],
        'fullcalendar': ['moment'],
        'ng-calendar': ['angular','moment'],
        'scrollbars': ['angular', 'angular-sanitize', 'ui-bootstrap'],
        'bootbox': ['jquery'],
        'core': ['jquery'],
        'codemirror': ['jquery'],

        //'myapp': ['angular', 'angularAMD'],

        //'app': ['angular', 'angular-cookies', 'angular-animate', 'angular-ui-router', 'angular-google-maps', 'angular-bootstrap', 'angular-route', 'angularAMD', 'ngload','async']
    },

    // kick start application
    deps: ['app']

});

