delete from SysMenuDms where MenuId in ('svinqpivot','svinqpivotsvccsv','svinqpivotsvcinv','svinqpivotsvcjrn','svinqpivotsvcmsi','svinqpivotsvctrans')
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivot','Pivot Service','svinquiry',8,2,'')
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivotsvctrans','Service Trans','svinqpivot',1,3,'inquiry/pvttrans')	
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivotsvcinv','Service Invoice','svinqpivot',2,3,'inquiry/pvtinv')
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivotsvcjrn','Service Journal','svinqpivot',3,3,'inquiry/pvtjournal')
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivotsvccsv','Customer Vehicle','svinqpivot',4,3,'inquiry/pvtcustomer')
insert into sysmenudms (menuid,MenuCaption, MenuHeader, MenuIndex,MenuLevel,MenuUrl)
values ('svinqpivotsvcmsi','Pivot Suzuki MSI','svinqpivot',5,3,'inquiry/pvtmsi')

delete from sysRoleMenu where MenuId in 
('svinqpivot','svinqpivotsvccsv','svinqpivotsvcinv','svinqpivotsvcjrn','svinqpivotsvcmsi','svinqpivotsvctrans')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivot','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivot','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivot','SERVICE')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvccsv','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvccsv','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvccsv','SERVICE')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcinv','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcinv','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcinv','SERVICE')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcjrn','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcjrn','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcjrn','SERVICE')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcmsi','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcmsi','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvcmsi','SERVICE')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvctrans','ADM')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvctrans','ADMIN')
insert into sysRoleMenu (MenuId,RoleId) values ('svinqpivotsvctrans','SERVICE')
