INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abdasempldept', N'Employee By Dept', N'abdashboard', 2, 2, N'dashboard/emplbydept')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abdasempldist', N'Employee Distribution', N'abdashboard', 1, 2, N'dashboard/empldist')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abdashboard', N'Dashboard', N'ab', 5, 1, NULL)
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abdept', N'Master Department', N'abmaster', 4, 2, N'master/dept')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abempl', N'Employee', N'ab', 2, 1, NULL)
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abholiday', N'Master Holiday', N'abmaster', 2, 2, N'master/holiday')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqempl', N'Personal List', N'abinqgen', 1, 3, N'inquiry/perslist')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqgen', N'General', N'abreport', 1, 2, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqpersachieve', N'Personal Position', N'abinqgen', 3, 3, N'inquiry/persachieve')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqpersinvalid', N'Personal Invalid', N'abinqgen', 4, 3, N'inquiry/persinvalid')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqpersmuta', N'Personal Mutation', N'abinqgen', 2, 3, N'inquiry/persmuta')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqsfm', N'Sales Force', N'abreport', 2, 2, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqsfmmutation', N'Data Mutation', N'abinqsfm', 2, 3, N'inquiry/sfmmutation')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqsfmpersinfo', N'Personal Information', N'abinqsfm', 1, 3, N'inquiry/sfmpersinfo')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abinqsfmtrend', N'Data Trend', N'abinqsfm', 3, 3, N'inquiry/sfmtrend')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'ablookup', N'Master Lookup', N'abmaster', 1, 2, N'master/lookup')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abmaster', N'Master', N'ab', 1, 1, NULL)
--INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abovertime', N'Maintain Overtime', N'abtrans', 3, 2, N'trans/overtime')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abpersinfo', N'Personal Information', N'abempl', 1, 1, N'empl/persinfo')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abposition', N'Master Position', N'abmaster', 5, 2, N'master/position')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abreport', N'Report', N'ab', 4, 1, NULL)
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abrptholiday', N'Master Holiday', N'abreportx', 1, 2, N'report/holiday')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abrptposition', N'Master Position', N'abreportx', 3, 2, N'report/position')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abrptshift', N'Master Shift', N'abreportx', 2, 2, N'report/shift')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'absalesinfo', N'Sales Information', N'abempl', 2, 1, N'empl/salesinfo')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abserviceinfo', N'Service Information', N'abempl', 3, 1, N'empl/serviceinfo')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abshift', N'Master Shift', N'abmaster', 3, 2, N'master/shift')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'abshiftmapping', N'Mapping Shift', N'abtrans', 1, 2, N'trans/shiftmap')