----------------------------------------------------------------- MENU MASTER -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spmaster', N'Master', N'sp', 	1	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppembelian', N'Ordering', N'sp', 	2	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenerimaan', N'Receiving', N'sp', 	3	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppengeluaran', N'Sales', N'sp', 	4	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppersediaan', N'Inventory', N'sp', 	5	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spstockopname', N'Stock Opname', N'sp', 	6	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sptutupperiode', N'Closing Period', N'sp', 	7	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spinquery', N'Inquiry', N'sp', 	8	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sputility', N'Utility', N'sp', 	9	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'splaporan', N'Report', N'sp', 	10	, 	1	, N'')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU REPORT -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx001', N'Report - Master', N'splaporan', 	1	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx002', N'Report - Ordering', N'splaporan', 	2	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx003', N'Report - Receiving', N'splaporan', 	3	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx004', N'Report - Inventory', N'splaporan', 	4	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx005', N'Report - Sales', N'splaporan', 	5	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx006', N'Report - Posting', N'splaporan', 	6	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx007', N'Report Stock Taking', N'splaporan', 	7	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx008', N'Report -Reports', N'splaporan', 	8	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx009', N'Report - Register', N'splaporan', 	9	, 	2	, N'')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU MASTER -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcmasteritem', N'Master Item', N'spmaster', 	101	, 	2	, N'master/masteritem')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcitemlokasi', N'Item Location', N'spmaster', 	102	, 	2	, N'master/itemlokasi')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcitemmodification', N'Item Modification (Subtitution Part)', N'spmaster', 	103	, 	2	, N'master/itemmodification')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcitemprice', N'Item Price', N'spmaster', 	104	, 	2	, N'master/itemprice')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcpartcpembelian', N'Part Campaign for Order', N'spmaster', 	105	, 	2	, N'master/campaignpembelian')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcpartcpenjualan', N'Part Campaign for Sale', N'spmaster', 	106	, 	2	, N'master/campaignpenjualan')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcmovingcode', N'Moving Code', N'spmaster', 	107	, 	2	, N'master/movingcode')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcglaccountmapping', N'GL Account Mapping', N'spmaster', 	108	, 	2	, N'master/glaccmapping')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcparameterorder', N'Parameter Order', N'spmaster', 	109	, 	2	, N'master/parameterorder')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spctargetpenjualan', N'Sales Target', N'spmaster', 	110	, 	2	, N'master/targetpenjualan')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcitemkonversi', N'Item Convertion', N'spmaster', 	111	, 	2	, N'master/itemkonversi')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcmastercompanyacc', N'Master Company Account', N'spmaster', 	112	, 	2	, N'master/companyacc')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU ORDERING -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spchpso', N'Process Suggestion Order', N'sppembelian', 	201	, 	2	, N'pembelian/pso')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spcheos', N'Entry Order Sparepart', N'sppembelian', 	202	, 	2	, N'pembelian/entryorder')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spmoos', N'Maintenance On Order Subtitusi', N'sppembelian', 	203	, 	2	, N'pembelian/maintenancesubtitusi')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spchmooo', N'Maintenance On Order PO', N'sppembelian', 	204	, 	2	, N'pembelian/maintenancepo')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU RECEIVING -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenedp', N'Entry Binning List', N'sppenerimaan', 	301	, 	2	, N'penerimaan/edp')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenwrs', N'Entry WRS', N'sppenerimaan', 	302	, 	2	, N'penerimaan/wrs')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenhpp', N'Entry HPP', N'sppenerimaan', 	303	, 	2	, N'penerimaan/hpp')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenclaimsupplier', N'Entry Claim Supplier', N'sppenerimaan', 	304	, 	2	, N'penerimaan/entryclaimsupplier')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sppenclaimvendor', N'Receiving Claim Vendor', N'sppenerimaan', 	305	, 	2	, N'penerimaan/claimvendor')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU SALES -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4001', N'Entry Stock Sales', N'sppengeluaran', 	401	, 	2	, N'pengeluaran/lnk4001')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4002', N'Picking List and Entry Picked Qty PL', N'sppengeluaran', 	402	, 	2	, N'pengeluaran/lnk4002')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4003', N'Generate Invoice', N'sppengeluaran', 	403	, 	2	, N'pengeluaran/fakturpenjualan')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4004', N'Generate Document Non Sales', N'sppengeluaran', 	404	, 	2	, N'pengeluaran/lnk4004')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4005', N'Maintenance Invoice', N'sppengeluaran', 	405	, 	2	, N'pengeluaran/lnk4005')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4006', N'Entry Sales Return', N'sppengeluaran', 	406	, 	2	, N'pengeluaran/lnk4006')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4007', N'Generate Service Document', N'sppengeluaran', 	407	, 	2	, N'pengeluaran/lnk4007')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4008', N'Entry Supply Slip Return', N'sppengeluaran', 	408	, 	2	, N'pengeluaran/lnk4008')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4009', N'Cancel BO Outstanding', N'sppengeluaran', 	409	, 	2	, N'pengeluaran/lnk4009')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4010', N'Entry Service Return', N'sppengeluaran', 	410	, 	2	, N'pengeluaran/lnk4010')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp4011', N'Cancel All BO Outstanding', N'sppengeluaran', 	411	, 	2	, N'pengeluaran/lnk4011')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU INVENTORY -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp5001', N'Inventory Adjustment', N'sppersediaan', 	501	, 	2	, N'persediaan/lnk5001')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp5002', N'Warehouse Transfer', N'sppersediaan', 	502	, 	2	, N'persediaan/lnk5002')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp5003', N'Reserved Sparepart', N'sppersediaan', 	503	, 	2	, N'persediaan/lnk5003')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU STOCK OPNAME -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6001', N'Inventory Form/Tag', N'spstockopname', 	601	, 	2	, N'stockopname/lnk6001')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6002', N'Blank Inventory Form/Tag', N'spstockopname', 	602	, 	2	, N'stockopname/lnk6002')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6003', N'Entry Inventory Form/Tag', N'spstockopname', 	603	, 	2	, N'stockopname/lnk6003')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6004', N'Cancel Blank Inventory Form/Tag', N'spstockopname', 	604	, 	2	, N'stockopname/lnk6004')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6005', N'Print Stock Taking', N'spstockopname', 	605	, 	2	, N'stockopname/lnk6005')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp6006', N'Posting Stock Taking to Master', N'spstockopname', 	606	, 	2	, N'stockopname/lnk6006')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU CLOSING PERIOD -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp7001', N'Closing Month', N'sptutupperiode', 	701	, 	2	, N'tutupperiode/lnk7001')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU INQUIRY -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8001', N'Inquiry Supplier', N'spinquery', 	801	, 	2	, N'inquiry/lnk8001')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8002', N'Inquiry Customer', N'spinquery', 	802	, 	2	, N'inquiry/lnk8002')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8003', N'Inquiry Item Sparepart', N'spinquery', 	803	, 	2	, N'inquiry/lnk8003')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8004', N'Inquiry Item Sparepart (HQ)', N'spinquery', 	804	, 	2	, N'inquiry/lnk8004')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8005', N'Inquiry Item Spareparts (SIMPLE)', N'spinquery', 	805	, 	2	, N'inquiry/lnk8005')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8006', N'Inquiry Receiving', N'spinquery', 	806	, 	2	, N'inquiry/lnk8006')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8007', N'Inquiry Sales Order', N'spinquery', 	807	, 	2	, N'inquiry/lnk8007')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8008', N'Inquiry Supply Slip', N'spinquery', 	808	, 	2	, N'inquiry/lnk8008')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8009', N'Inquiry DCS (Sparepart)', N'spinquery', 	809	, 	2	, N'inquiry/lnk8009')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp8010', N'Inquiry Sparepart', N'spinquery', 	810	, 	2	, N'inquiry/lnk8010')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------- SUB MENU UTILITY -------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9001', N'Upload File', N'sputility', 	901	, 	2	, N'utility/lnk9001')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9002', N'Switch Type Part User', N'sputility', 	902	, 	2	, N'utility/lnk9002')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9003', N'Send File', N'sputility', 	903	, 	2	, N'utility/lnk9003')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9004', N'Reset Stock Opname', N'sputility', 	904	, 	2	, N'utility/lnk9004')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9005', N'Upload From DCS', N'sputility', 	905	, 	2	, N'utility/lnk9005')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9006', N'Maintenance HPP', N'sputility', 	906	, 	2	, N'utility/lnk9006')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9007', N'Maintenance Type Part', N'sputility', 	907	, 	2	, N'utility/lnk9007')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'sp9008', N'Upload Dealer (Sparepart)', N'sputility', 	908	, 	2	, N'utility/lnk9008')
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx101', N'Daftar Master Sparepart', N'spx001', 	1	, 	3	, N'report/lnkx101')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx201', N'Suggestion Order', N'spx002', 	1	, 	3	, N'report/lnkx201')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx501', N'Daftar Picking List', N'spx005', 	1	, 	3	, N'report/lnkx501')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx801', N'Kartu Stock', N'spx008', 	1	, 	3	, N'report/lnkx801')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx901', N'Supply Slip', N'spx009', 	1	, 	3	, N'report/lnkx901')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx301', N'Binning List Pembelian', N'spx003', 	1	, 	3	, N'report/lnkx301')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx401', N'Inventory Adjustment', N'spx004', 	1	, 	3	, N'report/lnkx401')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx601', N'Analisa Sparepart Menurut ABC Class', N'spx006', 	1	, 	3	, N'report/lnkx601')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx701', N'Inventory Stock Taking Tag', N'spx007', 	1	, 	3	, N'report/lnkx701')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx702', N'Inventory Stock Taking Form', N'spx007', 	2	, 	3	, N'report/lnkx702')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx602', N'Analisa Sparepart Menurut Moving Code', N'spx006', 	2	, 	3	, N'report/lnkx602')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx402', N'Warehouse Transfer', N'spx004', 	2	, 	3	, N'report/lnkx402')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx302', N'WRS Pembelian', N'spx003', 	2	, 	3	, N'report/lnkx302')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx902', N'Supply Slip Outstanding', N'spx009', 	2	, 	3	, N'report/lnkx902')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx802', N'Daftar Item Dengan Penjualan Terbaik', N'spx008', 	2	, 	3	, N'report/lnkx802')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx502', N'Daftar Pengeluaran Stock', N'spx005', 	2	, 	3	, N'report/lnkx502')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx202', N'Daftar Pesanan Spaprepat', N'spx002', 	2	, 	3	, N'report/lnkx202')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx102', N'List Master Subtitusi', N'spx001', 	2	, 	3	, N'report/lnkx102')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx103', N'Daftar Perubahan Outstanding Pesanan', N'spx001', 	3	, 	3	, N'report/lnkx103')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx203', N'Daftar On Order Per Part', N'spx002', 	3	, 	3	, N'report/lnkx203')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx503', N'Daftar Faktur Penjualan', N'spx005', 	3	, 	3	, N'report/lnkx503')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx803', N'Daftar Analisa Service Ratio Per Pelanggan', N'spx008', 	3	, 	3	, N'report/lnkx803')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx903', N'History Supply Slip Outstanding', N'spx009', 	3	, 	3	, N'report/lnkx903')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx303', N'Entry HPP', N'spx003', 	3	, 	3	, N'report/lnkx303')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx403', N'Reserved Sparepart', N'spx004', 	3	, 	3	, N'report/lnkx403')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx603', N'Mutasi Stock Bulanan', N'spx006', 	3	, 	3	, N'report/lnkx603')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx703', N'Analisa Stock Taking', N'spx007', 	3	, 	3	, N'report/lnkx703')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx704', N'Daftar Inventory Form/Tag', N'spx007', 	4	, 	3	, N'report/lnkx704')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx304', N'Claim Vendor Form', N'spx003', 	4	, 	3	, N'report/lnkx304')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx904', N'Register Lampiran Faktur Non Penjualan', N'spx009', 	4	, 	3	, N'report/lnkx904')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx804', N'Daftar Part Per MC, ABC Class & Demand', N'spx008', 	4	, 	3	, N'report/lnkx804')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx504', N'Daftar Lampiran Dokumen Nonpenjualan', N'spx005', 	4	, 	3	, N'report/lnkx504')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx505', N'Daftar Lampiran Faktur Penjualan', N'spx005', 	5	, 	3	, N'report/lnkx505')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx805', N'Daftar Ringkasan Service Ratio', N'spx008', 	5	, 	3	, N'report/lnkx805')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx905', N'Register Bon Pengeluaran Sparepart', N'spx009', 	5	, 	3	, N'report/lnkx905')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx305', N'Receiving Claim Vendor Form', N'spx003', 	5	, 	3	, N'report/lnkx305')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx705', N'Daftar Outstanding Inventory Form/Tag', N'spx007', 	5	, 	3	, N'report/lnkx705')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx706', N'Daftar Transaksi Stock Taking Harian', N'spx007', 	6	, 	3	, N'report/lnkx706')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx906', N'Register Penjualan (Tunai & Kredit)', N'spx009', 	6	, 	3	, N'report/lnkx906')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx806', N'Daftar Penjualan Per Pelanggan', N'spx008', 	6	, 	3	, N'report/lnkx806')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx506', N'Daftar Sales Retur Memo', N'spx005', 	6	, 	3	, N'report/lnkx506')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx507', N'Daftar Cancel Faktur Service', N'spx005', 	7	, 	3	, N'report/lnkx507')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx807', N'Daftar Barang Yang di Pinjam', N'spx008', 	7	, 	3	, N'report/lnkx807')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx907', N'Register Bon Pengeluaran Sparepart Outstanding', N'spx009', 	7	, 	3	, N'report/lnkx907')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx908', N'Register Penjualan Per Pelanggan (Kredit dan Tunai)', N'spx009', 	8	, 	3	, N'report/lnkx908')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx808', N'Daftar Barang Yang Harus di Kembalikan', N'spx008', 	8	, 	3	, N'report/lnkx808')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx508', N'Daftar Slip Supply Retur Memo', N'spx005', 	8	, 	3	, N'report/lnkx508')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx509', N'Daftar Outstanding Supply Slip', N'spx005', 	9	, 	3	, N'report/lnkx509')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx809', N'Daftar Perubahan Harga Potongan, Beli dan Jual', N'spx008', 	9	, 	3	, N'report/lnkx809')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx909', N'Register Penjualan', N'spx009', 	9	, 	3	, N'report/lnkx909')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx910', N'Register Faktur Penjualan (HQ)', N'spx009', 	10	, 	3	, N'report/lnkx910')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx810', N'Daftar Perubahan Average Cost', N'spx008', 	10	, 	3	, N'report/lnkx810')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx510', N'Daftar Back Order Bulanan Per Langganan', N'spx005', 	10	, 	3	, N'report/lnkx510')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx511', N'Daftar Back Order Harian Per Part', N'spx005', 	11	, 	3	, N'report/lnkx511')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx811', N'Daftar Pajak Keluaran', N'spx008', 	11	, 	3	, N'report/lnkx811')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx911', N'Register Retur Penjualan', N'spx009', 	11	, 	3	, N'report/lnkx911')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx912', N'Register Retur Supply Slip', N'spx009', 	12	, 	3	, N'report/lnkx912')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx812', N'Daftar Part per Nomor Part', N'spx008', 	12	, 	3	, N'report/lnkx812')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx512', N'Daftar Back Order Harian Langganan', N'spx005', 	12	, 	3	, N'report/lnkx512')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx513', N'Daftar Back Order Cancel', N'spx005', 	13	, 	3	, N'report/lnkx513')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx813', N'Lampiran Faktur untuk Supply Slip dan Unit', N'spx008', 	13	, 	3	, N'report/lnkx813')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx913', N'Register Faktur Penjualan Per Pelanggan (HQ)', N'spx009', 	13	, 	3	, N'report/lnkx913')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx914', N'Register Detail Retur Penjualan', N'spx009', 	14	, 	3	, N'report/lnkx914')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx814', N'Stock Information', N'spx008', 	14	, 	3	, N'report/lnkx814')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx514', N'Daftar Faktur Penjualan (Pre-printed)', N'spx005', 	14	, 	3	, N'report/lnkx514')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx815', N'Laporan Penjualan per Class, Area dan Lokasi', N'spx008', 	15	, 	3	, N'report/lnkx815')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx915', N'Register Claim Form', N'spx009', 	15	, 	3	, N'report/lnkx915')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx916', N'Register Claim Cancel', N'spx009', 	16	, 	3	, N'report/lnkx916')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx816', N'Laporan Aktivitas Transaksi', N'spx008', 	16	, 	3	, N'report/lnkx816')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx817', N'Daftar Over Stock', N'spx008', 	17	, 	3	, N'report/lnkx817')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx917', N'Daftar Outstanding Claim', N'spx009', 	17	, 	3	, N'report/lnkx917')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx918', N'Register Pesanan Sparepart', N'spx009', 	18	, 	3	, N'report/lnkx918')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx818', N'Laporan Laba Rugi', N'spx008', 	18	, 	3	, N'report/lnkx818')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx819', N'Laporan Rekapitulasi Omzet', N'spx008', 	19	, 	3	, N'report/lnkx819')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx920', N'Register Warehouse Receiving Sheet', N'spx009', 	20	, 	3	, N'report/lnkx920')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx921', N'Register HPP Sparepart', N'spx009', 	21	, 	3	, N'report/lnkx921')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx922', N'Register Inventory Adjustment', N'spx009', 	22	, 	3	, N'report/lnkx922')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx923', N'Register Warehouse Transfer', N'spx009', 	23	, 	3	, N'report/lnkx923')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx924', N'Daftar Dokumen Pending', N'spx009', 	24	, 	3	, N'report/lnkx924')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx925', N'Report untuk Kantor Pajak', N'spx009', 	25	, 	3	, N'report/lnkx925')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx926', N'Pelanggan Overlimit', N'spx009', 	26	, 	3	, N'report/lnkx926')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx927', N'Register Rekon Sparepart', N'spx009', 	27	, 	3	, N'report/lnkx927')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'spx928', N'Register Perubahan Average Cost', N'spx009', 	28	, 	3	, N'report/lnkx928')