INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtrans', N'Transaction', N'sv', 	2	, 	0	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svsrs', N'S R S', N'sv', 	3	, 	0	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl', N'Template', N'sv', 	0	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svmaster', N'Master', N'sv', 	1	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svrefser', N'Referensi Service', N'svmaster', 	2	, 	1	, N'master/ref')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svinquiry', N'Inquiry', N'sv', 	4	, 	1	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svreport', N'Report', N'sv', 	5	, 	1	, N'')

INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqJobMonitoring', N'Pemantauan Pekerjaan', N'svinquiry', 	0	, 	2	, N'inquiry/jobmonitoring')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqWorkOrder', N'Surat Perintah Kerja', N'svinquiry', 	1	, 	2	, N'inquiry/workorder')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svservice', N'Perawatan Kendaraan', N'svtrans', 	1	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl1', N'Title & Toolbar', N'svtmpl', 	1	, 	2	, N'template/tmpl1')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl2', N'Textbox & TextArea', N'svtmpl', 	2	, 	2	, N'template/tmpl2')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svksg', N'KSG', N'svtrans', 	2	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqHistServiceVehicle', N'Riwayat Perawatan Kendaraan', N'svinquiry', 	2	, 	2	, N'inquiry/histservicevehicle')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtipepemb', N'Tipe Pembayaran', N'svmaster', 	2	, 	2	, N'master/tipemb')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svclaim', N'Warranty Claim', N'svtrans', 	3	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqPartMaterial', N'Part dan Material', N'svinquiry', 	3	, 	2	, N'inquiry/partmaterial')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl3', N'Spinner & Datepicker', N'svtmpl', 	3	, 	2	, N'template/tmpl3')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl4', N'Select & Switch', N'svtmpl', 	4	, 	2	, N'template/tmpl4')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svpaket', N'Paket Service', N'svtrans', 	4	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqUnitInfo', N'Inquiry Informasi Kendaraan', N'svinquiry', 	4	, 	2	, N'inquiry/unitinfo')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInqMsi', N'Inquiry Suzuki MSI', N'svinquiry', 	5	, 	2	, N'inquiry/inqmsi')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl5', N'span, 8 columns fluid width', N'svtmpl', 	5	, 	2	, N'template/tmpl5')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl6', N'Popup', N'svtmpl', 	6	, 	2	, N'tmpl/tmpl6.js')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtmpl7', N'Multi Panel', N'svtmpl', 	7	, 	2	, N'tmpl/tmpl7.js')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svspkinput', N'Input SPK', N'svservice', 	1	, 	3	, N'trans/spk')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svksgspk', N'Get KSG from SPK', N'svksg', 	1	, 	3	, N'trans/ksgspk')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInputInfoClaimSPK', N'Input Infromation Claim (SPK)', N'svclaim', 	1	, 	3	, N'trans/inputinfoclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgetpackage', N'Get Paket Service', N'svpaket', 	1	, 	3	, N'trans/getpackage')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgenpackage', N'Generate Paket Service', N'svpaket', 	2	, 	3	, N'trans/genpackage')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svamekanik', N'Alokasi Mekanik', N'svservice', 	2	, 	3	, N'trans/mekanik')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInputInfoClaimINV', N'Input Infromation Claim (INV)', N'svclaim', 	2	, 	3	, N'trans/inputinfoclaiminv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svksginv', N'Get KSG from Invoice', N'svksg', 	2	, 	3	, N'trans/ksginv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svstl', N'Stall', N'svmaster', 	3	, 	3	, N'master/stall')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInputInfoClaimFromSPK', N'Input Claim From SPK', N'svclaim', 	3	, 	3	, N'trans/inputinfoclaimfromspk')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svInputWarrantyClaim', N'Input Warranty Claim', N'svclaim', 	3	, 	3	, N'trans/inputwarrantyclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgetksg', N'Get KSG', N'svksg', 	3	, 	3	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svviewjoborder', N'Simulasi Harga SPK', N'svservice', 	3	, 	3	, N'trans/viewjoborder')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svGetWarrantyClaim', N'Get Warranty Claim (SPK/INV)', N'svclaim', 	4	, 	3	, N'trans/getwarrantyclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svinputksg', N'Input KSG', N'svksg', 	4	, 	3	, N'trans/inputksg')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svmaintainspk', N'Maintenance SPK', N'svservice', 	4	, 	3	, N'trans/maintainspk')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svsubcon', N'Input Pesanan Pekerjaan Luar', N'svservice', 	5	, 	3	, N'trans/subcon')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svuplksg', N'Upload KSG', N'svksg', 	5	, 	3	, N'trans/uploadksg')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svUploadDataClaim', N'Upload Calim Data (Cabang/Sub-Delaer)', N'svclaim', 	5	, 	3	, N'trans/uploadclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svsubconrcv', N'Input Penerimaan Pekerjaan Luar', N'svservice', 	6	, 	3	, N'trans/subconrcv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svGenerateDataClaim', N'Generate Claim Data', N'svclaim', 	6	, 	3	, N'trans/generateclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgenksgspk', N'Generate KSG From SPK', N'svksg', 	6	, 	3	, N'trans/genksgspk')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgenksg', N'Generate Data KSG', N'svksg', 	7	, 	3	, N'trans/genksg')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svinvoice', N'Proses Invoice', N'svservice', 	7	, 	3	, N'trans/invoice')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svReceiveDataClaim', N'Receive Claim Data', N'svclaim', 	7	, 	3	, N'trans/receiveclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svMaintainWarrantyClaim', N'Maintenance Claim', N'svclaim', 	8	, 	3	, N'trans/maintainwarrantyclaim')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgenfpj', N'Generate Consolidation Tax Invoice', N'svservice', 	8	, 	3	, N'trans/genfpj')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgenfpjstd', N'Generate Standard Tax Invoice', N'svservice', 	9	, 	3	, N'trans/genfpjstd')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svmainksg', N'Maintenance KSG', N'svksg', 	9	, 	3	, N'trans/mainksg')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svmaintainfpj', N'Maintain Invoice Tax', N'svservice', 	10	, 	3	, N'trans/maintainfpj')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svmaintaininv', N'Maintain Invoice', N'svservice', 	11	, 	3	, N'trans/maintaininv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svretur', N'Retur Service', N'svservice', 	12	, 	3	, N'trans/retur')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svcancelinvoice', N'Cancel Invoice', N'svservice', 	13	, 	3	, N'trans/cancelinvoice')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svinvoicebatch', N'Process Invoice - Batch', N'svservice', 	13	, 	3	, N'trans/invoicebatch')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svwaktukerja', N'Waktu Kerja', N'svmaster', 	4	, 	4	, N'master/wkt')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svabsenmekanik', N'Kehadiran Mekanik', N'svmaster', 	5	, 	5	, N'master/absen')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svgaransi', N'Garansi', N'svmaster', 	6	, 	6	, N'master/garansi')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svcampaign', N'Campaign', N'svmaster', 	7	, 	7	, N'master/campaign')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svkerja', N'Pekerjaan', N'svmaster', 	8	, 	8	, N'master/kerja')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtarifksg', N'Tarif Kupon Service Gratis (KSG)', N'svmaster', 	9	, 	9	, N'master/ksg')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtarifjasa', N'Tarif Jasa', N'svmaster', 	10	, 	10	, N'master/tafja')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svkdanp', N'Kendaraan dan Pelanggan', N'svmaster', 	11	, 	11	, N'master/kdanp')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svkontakservice', N'Kontrak Service', N'svmaster', 	12	, 	12	, N'master/konserv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svklub', N'Klub', N'svmaster', 	13	, 	13	, N'master/klub')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svevent', N'Event', N'svmaster', 	14	, 	14	, N'master/evn')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svpaketservice', N'Paket Service', N'svmaster', 	15	, 	15	, N'master/pakserv')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svpenpaketservice', N'Pendaftaran Paket Service', N'svmaster', 	16	, 	16	, N'master/pps')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svtarget', N'Target', N'svmaster', 	17	, 	17	, N'master/target')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svaccount', N'Account', N'svmaster', 	18	, 	18	, N'master/acc')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svpencampaign', N'Pendaftaran Campaign', N'svmaster', 	19	, 	19	, N'master/pcampaign')

------------------------------------------------------ SUB MENU REPORT --------------------------------------------------------------------------------------
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svrptregister', N'Register', N'svreport', 	1	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svrptreport', N'Report', N'svreport', 	2	, 	2	, N'')
INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svrptservice', N'Service', N'svreport', 	3	, 	2	, N'')

INSERT [dbo].[SysMenuDms] ([MenuId], [MenuCaption], [MenuHeader], [MenuIndex], [MenuLevel], [MenuUrl]) VALUES (N'svrptregbookest', N'Register Booking / Estimation', N'svrptregister', 	1	, 	3	, N'report/register/regbooking')

-------------------------------------------------------------------------------------------------------------------------------------------------------------