//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimDms.Common.DcsWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DcsDownloadFile", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DcsDownloadFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataID {
            get {
                return this.DataIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DataIDField, value) != true)) {
                    this.DataIDField = value;
                    this.RaisePropertyChanged("DataID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DcsWs.DcsWsSoap")]
    public interface DcsWsSoap {
        
        // CODEGEN: Generating message contract since element name DataID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendToDcs", ReplyAction="*")]
        SimDms.Common.DcsWs.SendToDcsResponse SendToDcs(SimDms.Common.DcsWs.SendToDcsRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveData", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDataResponse RetrieveData(SimDms.Common.DcsWs.RetrieveDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveDownloadData", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDownloadDataResponse RetrieveDownloadData(SimDms.Common.DcsWs.RetrieveDownloadDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveDownloadByLastID", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDownloadByLastIDResponse RetrieveDownloadByLastID(SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        SimDms.Common.DcsWs.GetDataResponse GetData(SimDms.Common.DcsWs.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveUploadData", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveUploadDataResponse RetrieveUploadData(SimDms.Common.DcsWs.RetrieveUploadDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveUploadDataV2", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveUploadDataV2Response RetrieveUploadDataV2(SimDms.Common.DcsWs.RetrieveUploadDataV2Request request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUploadDataStatus", ReplyAction="*")]
        SimDms.Common.DcsWs.UpdateUploadDataStatusResponse UpdateUploadDataStatus(SimDms.Common.DcsWs.UpdateUploadDataStatusRequest request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDownloadDataStatus", ReplyAction="*")]
        SimDms.Common.DcsWs.UpdateDownloadDataStatusResponse UpdateDownloadDataStatus(SimDms.Common.DcsWs.UpdateDownloadDataStatusRequest request);
        
        // CODEGEN: Generating message contract since element name DataID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveDownloadByDataID", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDownloadByDataIDResponse RetrieveDownloadByDataID(SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequest request);
        
        // CODEGEN: Generating message contract since element name DataID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveDownloadByRangeDataID", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDResponse RetrieveDownloadByRangeDataID(SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValid", ReplyAction="*")]
        bool IsValid();
        
        // CODEGEN: Generating message contract since element name DataID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveDcsDownloadFile", ReplyAction="*")]
        SimDms.Common.DcsWs.RetrieveDcsDownloadFileResponse RetrieveDcsDownloadFile(SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToDcsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToDcs", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.SendToDcsRequestBody Body;
        
        public SendToDcsRequest() {
        }
        
        public SendToDcsRequest(SimDms.Common.DcsWs.SendToDcsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToDcsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProdType;
        
        public SendToDcsRequestBody() {
        }
        
        public SendToDcsRequestBody(string DataID, string CustCode, string Content, string ProdType) {
            this.DataID = DataID;
            this.CustCode = CustCode;
            this.Content = Content;
            this.ProdType = ProdType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToDcsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToDcsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.SendToDcsResponseBody Body;
        
        public SendToDcsResponse() {
        }
        
        public SendToDcsResponse(SimDms.Common.DcsWs.SendToDcsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToDcsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendToDcsResult;
        
        public SendToDcsResponseBody() {
        }
        
        public SendToDcsResponseBody(string SendToDcsResult) {
            this.SendToDcsResult = SendToDcsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveData", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDataRequestBody Body;
        
        public RetrieveDataRequest() {
        }
        
        public RetrieveDataRequest(SimDms.Common.DcsWs.RetrieveDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime ToDate;
        
        public RetrieveDataRequestBody() {
        }
        
        public RetrieveDataRequestBody(string CustCode, string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            this.CustCode = CustCode;
            this.DataID = DataID;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDataResponseBody Body;
        
        public RetrieveDataResponse() {
        }
        
        public RetrieveDataResponse(SimDms.Common.DcsWs.RetrieveDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDataResult;
        
        public RetrieveDataResponseBody() {
        }
        
        public RetrieveDataResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveDataResult) {
            this.RetrieveDataResult = RetrieveDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadData", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadDataRequestBody Body;
        
        public RetrieveDownloadDataRequest() {
        }
        
        public RetrieveDownloadDataRequest(SimDms.Common.DcsWs.RetrieveDownloadDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime ToDate;
        
        public RetrieveDownloadDataRequestBody() {
        }
        
        public RetrieveDownloadDataRequestBody(string CustCode, string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            this.CustCode = CustCode;
            this.DataID = DataID;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadDataResponseBody Body;
        
        public RetrieveDownloadDataResponse() {
        }
        
        public RetrieveDownloadDataResponse(SimDms.Common.DcsWs.RetrieveDownloadDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadDataResult;
        
        public RetrieveDownloadDataResponseBody() {
        }
        
        public RetrieveDownloadDataResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadDataResult) {
            this.RetrieveDownloadDataResult = RetrieveDownloadDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByLastIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByLastID", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequestBody Body;
        
        public RetrieveDownloadByLastIDRequest() {
        }
        
        public RetrieveDownloadByLastIDRequest(SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByLastIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long LastID;
        
        public RetrieveDownloadByLastIDRequestBody() {
        }
        
        public RetrieveDownloadByLastIDRequestBody(string CustCode, string DataID, long LastID) {
            this.CustCode = CustCode;
            this.DataID = DataID;
            this.LastID = LastID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByLastIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByLastIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByLastIDResponseBody Body;
        
        public RetrieveDownloadByLastIDResponse() {
        }
        
        public RetrieveDownloadByLastIDResponse(SimDms.Common.DcsWs.RetrieveDownloadByLastIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByLastIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByLastIDResult;
        
        public RetrieveDownloadByLastIDResponseBody() {
        }
        
        public RetrieveDownloadByLastIDResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByLastIDResult) {
            this.RetrieveDownloadByLastIDResult = RetrieveDownloadByLastIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(SimDms.Common.DcsWs.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long ID;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string CustCode, string DataID, long ID) {
            this.CustCode = CustCode;
            this.DataID = DataID;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(SimDms.Common.DcsWs.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveUploadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveUploadData", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveUploadDataRequestBody Body;
        
        public RetrieveUploadDataRequest() {
        }
        
        public RetrieveUploadDataRequest(SimDms.Common.DcsWs.RetrieveUploadDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveUploadDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long LastId;
        
        public RetrieveUploadDataRequestBody() {
        }
        
        public RetrieveUploadDataRequestBody(string CustCode, string DataId, long LastId) {
            this.CustCode = CustCode;
            this.DataId = DataId;
            this.LastId = LastId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveUploadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveUploadDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveUploadDataResponseBody Body;
        
        public RetrieveUploadDataResponse() {
        }
        
        public RetrieveUploadDataResponse(SimDms.Common.DcsWs.RetrieveUploadDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveUploadDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveUploadDataResult;
        
        public RetrieveUploadDataResponseBody() {
        }
        
        public RetrieveUploadDataResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveUploadDataResult) {
            this.RetrieveUploadDataResult = RetrieveUploadDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveUploadDataV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveUploadDataV2", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveUploadDataV2RequestBody Body;
        
        public RetrieveUploadDataV2Request() {
        }
        
        public RetrieveUploadDataV2Request(SimDms.Common.DcsWs.RetrieveUploadDataV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveUploadDataV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long LastId;
        
        public RetrieveUploadDataV2RequestBody() {
        }
        
        public RetrieveUploadDataV2RequestBody(string CustCode, string DataId, long LastId) {
            this.CustCode = CustCode;
            this.DataId = DataId;
            this.LastId = LastId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveUploadDataV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveUploadDataV2Response", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveUploadDataV2ResponseBody Body;
        
        public RetrieveUploadDataV2Response() {
        }
        
        public RetrieveUploadDataV2Response(SimDms.Common.DcsWs.RetrieveUploadDataV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveUploadDataV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveUploadDataV2Result;
        
        public RetrieveUploadDataV2ResponseBody() {
        }
        
        public RetrieveUploadDataV2ResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveUploadDataV2Result) {
            this.RetrieveUploadDataV2Result = RetrieveUploadDataV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUploadDataStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUploadDataStatus", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.UpdateUploadDataStatusRequestBody Body;
        
        public UpdateUploadDataStatusRequest() {
        }
        
        public UpdateUploadDataStatusRequest(SimDms.Common.DcsWs.UpdateUploadDataStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUploadDataStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateUploadDataStatusRequestBody() {
        }
        
        public UpdateUploadDataStatusRequestBody(long id, string status) {
            this.id = id;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUploadDataStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUploadDataStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.UpdateUploadDataStatusResponseBody Body;
        
        public UpdateUploadDataStatusResponse() {
        }
        
        public UpdateUploadDataStatusResponse(SimDms.Common.DcsWs.UpdateUploadDataStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUploadDataStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateUploadDataStatusResult;
        
        public UpdateUploadDataStatusResponseBody() {
        }
        
        public UpdateUploadDataStatusResponseBody(string UpdateUploadDataStatusResult) {
            this.UpdateUploadDataStatusResult = UpdateUploadDataStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDownloadDataStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDownloadDataStatus", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.UpdateDownloadDataStatusRequestBody Body;
        
        public UpdateDownloadDataStatusRequest() {
        }
        
        public UpdateDownloadDataStatusRequest(SimDms.Common.DcsWs.UpdateDownloadDataStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDownloadDataStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateDownloadDataStatusRequestBody() {
        }
        
        public UpdateDownloadDataStatusRequestBody(long id, string status) {
            this.id = id;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDownloadDataStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDownloadDataStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.UpdateDownloadDataStatusResponseBody Body;
        
        public UpdateDownloadDataStatusResponse() {
        }
        
        public UpdateDownloadDataStatusResponse(SimDms.Common.DcsWs.UpdateDownloadDataStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDownloadDataStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateDownloadDataStatusResult;
        
        public UpdateDownloadDataStatusResponseBody() {
        }
        
        public UpdateDownloadDataStatusResponseBody(string UpdateDownloadDataStatusResult) {
            this.UpdateDownloadDataStatusResult = UpdateDownloadDataStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByDataIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByDataID", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequestBody Body;
        
        public RetrieveDownloadByDataIDRequest() {
        }
        
        public RetrieveDownloadByDataIDRequest(SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByDataIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long LastID;
        
        public RetrieveDownloadByDataIDRequestBody() {
        }
        
        public RetrieveDownloadByDataIDRequestBody(string DataID, long LastID) {
            this.DataID = DataID;
            this.LastID = LastID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByDataIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByDataIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByDataIDResponseBody Body;
        
        public RetrieveDownloadByDataIDResponse() {
        }
        
        public RetrieveDownloadByDataIDResponse(SimDms.Common.DcsWs.RetrieveDownloadByDataIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByDataIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByDataIDResult;
        
        public RetrieveDownloadByDataIDResponseBody() {
        }
        
        public RetrieveDownloadByDataIDResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByDataIDResult) {
            this.RetrieveDownloadByDataIDResult = RetrieveDownloadByDataIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByRangeDataIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByRangeDataID", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequestBody Body;
        
        public RetrieveDownloadByRangeDataIDRequest() {
        }
        
        public RetrieveDownloadByRangeDataIDRequest(SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByRangeDataIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long fromID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long toID;
        
        public RetrieveDownloadByRangeDataIDRequestBody() {
        }
        
        public RetrieveDownloadByRangeDataIDRequestBody(string DataID, long fromID, long toID) {
            this.DataID = DataID;
            this.fromID = fromID;
            this.toID = toID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDownloadByRangeDataIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDownloadByRangeDataIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDResponseBody Body;
        
        public RetrieveDownloadByRangeDataIDResponse() {
        }
        
        public RetrieveDownloadByRangeDataIDResponse(SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDownloadByRangeDataIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByRangeDataIDResult;
        
        public RetrieveDownloadByRangeDataIDResponseBody() {
        }
        
        public RetrieveDownloadByRangeDataIDResponseBody(SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByRangeDataIDResult) {
            this.RetrieveDownloadByRangeDataIDResult = RetrieveDownloadByRangeDataIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDcsDownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDcsDownloadFile", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequestBody Body;
        
        public RetrieveDcsDownloadFileRequest() {
        }
        
        public RetrieveDcsDownloadFileRequest(SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDcsDownloadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime ToDate;
        
        public RetrieveDcsDownloadFileRequestBody() {
        }
        
        public RetrieveDcsDownloadFileRequestBody(string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            this.DataID = DataID;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveDcsDownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveDcsDownloadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimDms.Common.DcsWs.RetrieveDcsDownloadFileResponseBody Body;
        
        public RetrieveDcsDownloadFileResponse() {
        }
        
        public RetrieveDcsDownloadFileResponse(SimDms.Common.DcsWs.RetrieveDcsDownloadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveDcsDownloadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimDms.Common.DcsWs.DcsDownloadFile[] RetrieveDcsDownloadFileResult;
        
        public RetrieveDcsDownloadFileResponseBody() {
        }
        
        public RetrieveDcsDownloadFileResponseBody(SimDms.Common.DcsWs.DcsDownloadFile[] RetrieveDcsDownloadFileResult) {
            this.RetrieveDcsDownloadFileResult = RetrieveDcsDownloadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DcsWsSoapChannel : SimDms.Common.DcsWs.DcsWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DcsWsSoapClient : System.ServiceModel.ClientBase<SimDms.Common.DcsWs.DcsWsSoap>, SimDms.Common.DcsWs.DcsWsSoap {
        
        public DcsWsSoapClient() {
        }
        
        public DcsWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DcsWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcsWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcsWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.SendToDcsResponse SimDms.Common.DcsWs.DcsWsSoap.SendToDcs(SimDms.Common.DcsWs.SendToDcsRequest request) {
            return base.Channel.SendToDcs(request);
        }
        
        public string SendToDcs(string DataID, string CustCode, string Content, string ProdType) {
            SimDms.Common.DcsWs.SendToDcsRequest inValue = new SimDms.Common.DcsWs.SendToDcsRequest();
            inValue.Body = new SimDms.Common.DcsWs.SendToDcsRequestBody();
            inValue.Body.DataID = DataID;
            inValue.Body.CustCode = CustCode;
            inValue.Body.Content = Content;
            inValue.Body.ProdType = ProdType;
            SimDms.Common.DcsWs.SendToDcsResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).SendToDcs(inValue);
            return retVal.Body.SendToDcsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDataResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveData(SimDms.Common.DcsWs.RetrieveDataRequest request) {
            return base.Channel.RetrieveData(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveData(string CustCode, string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            SimDms.Common.DcsWs.RetrieveDataRequest inValue = new SimDms.Common.DcsWs.RetrieveDataRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDataRequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataID = DataID;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            SimDms.Common.DcsWs.RetrieveDataResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveData(inValue);
            return retVal.Body.RetrieveDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDownloadDataResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveDownloadData(SimDms.Common.DcsWs.RetrieveDownloadDataRequest request) {
            return base.Channel.RetrieveDownloadData(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadData(string CustCode, string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            SimDms.Common.DcsWs.RetrieveDownloadDataRequest inValue = new SimDms.Common.DcsWs.RetrieveDownloadDataRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDownloadDataRequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataID = DataID;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            SimDms.Common.DcsWs.RetrieveDownloadDataResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveDownloadData(inValue);
            return retVal.Body.RetrieveDownloadDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDownloadByLastIDResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveDownloadByLastID(SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequest request) {
            return base.Channel.RetrieveDownloadByLastID(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByLastID(string CustCode, string DataID, long LastID) {
            SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequest inValue = new SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDownloadByLastIDRequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataID = DataID;
            inValue.Body.LastID = LastID;
            SimDms.Common.DcsWs.RetrieveDownloadByLastIDResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveDownloadByLastID(inValue);
            return retVal.Body.RetrieveDownloadByLastIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.GetDataResponse SimDms.Common.DcsWs.DcsWsSoap.GetData(SimDms.Common.DcsWs.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(string CustCode, string DataID, long ID) {
            SimDms.Common.DcsWs.GetDataRequest inValue = new SimDms.Common.DcsWs.GetDataRequest();
            inValue.Body = new SimDms.Common.DcsWs.GetDataRequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataID = DataID;
            inValue.Body.ID = ID;
            SimDms.Common.DcsWs.GetDataResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveUploadDataResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveUploadData(SimDms.Common.DcsWs.RetrieveUploadDataRequest request) {
            return base.Channel.RetrieveUploadData(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveUploadData(string CustCode, string DataId, long LastId) {
            SimDms.Common.DcsWs.RetrieveUploadDataRequest inValue = new SimDms.Common.DcsWs.RetrieveUploadDataRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveUploadDataRequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataId = DataId;
            inValue.Body.LastId = LastId;
            SimDms.Common.DcsWs.RetrieveUploadDataResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveUploadData(inValue);
            return retVal.Body.RetrieveUploadDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveUploadDataV2Response SimDms.Common.DcsWs.DcsWsSoap.RetrieveUploadDataV2(SimDms.Common.DcsWs.RetrieveUploadDataV2Request request) {
            return base.Channel.RetrieveUploadDataV2(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveUploadDataV2(string CustCode, string DataId, long LastId) {
            SimDms.Common.DcsWs.RetrieveUploadDataV2Request inValue = new SimDms.Common.DcsWs.RetrieveUploadDataV2Request();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveUploadDataV2RequestBody();
            inValue.Body.CustCode = CustCode;
            inValue.Body.DataId = DataId;
            inValue.Body.LastId = LastId;
            SimDms.Common.DcsWs.RetrieveUploadDataV2Response retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveUploadDataV2(inValue);
            return retVal.Body.RetrieveUploadDataV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.UpdateUploadDataStatusResponse SimDms.Common.DcsWs.DcsWsSoap.UpdateUploadDataStatus(SimDms.Common.DcsWs.UpdateUploadDataStatusRequest request) {
            return base.Channel.UpdateUploadDataStatus(request);
        }
        
        public string UpdateUploadDataStatus(long id, string status) {
            SimDms.Common.DcsWs.UpdateUploadDataStatusRequest inValue = new SimDms.Common.DcsWs.UpdateUploadDataStatusRequest();
            inValue.Body = new SimDms.Common.DcsWs.UpdateUploadDataStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            SimDms.Common.DcsWs.UpdateUploadDataStatusResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).UpdateUploadDataStatus(inValue);
            return retVal.Body.UpdateUploadDataStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.UpdateDownloadDataStatusResponse SimDms.Common.DcsWs.DcsWsSoap.UpdateDownloadDataStatus(SimDms.Common.DcsWs.UpdateDownloadDataStatusRequest request) {
            return base.Channel.UpdateDownloadDataStatus(request);
        }
        
        public string UpdateDownloadDataStatus(long id, string status) {
            SimDms.Common.DcsWs.UpdateDownloadDataStatusRequest inValue = new SimDms.Common.DcsWs.UpdateDownloadDataStatusRequest();
            inValue.Body = new SimDms.Common.DcsWs.UpdateDownloadDataStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            SimDms.Common.DcsWs.UpdateDownloadDataStatusResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).UpdateDownloadDataStatus(inValue);
            return retVal.Body.UpdateDownloadDataStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDownloadByDataIDResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveDownloadByDataID(SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequest request) {
            return base.Channel.RetrieveDownloadByDataID(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByDataID(string DataID, long LastID) {
            SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequest inValue = new SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDownloadByDataIDRequestBody();
            inValue.Body.DataID = DataID;
            inValue.Body.LastID = LastID;
            SimDms.Common.DcsWs.RetrieveDownloadByDataIDResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveDownloadByDataID(inValue);
            return retVal.Body.RetrieveDownloadByDataIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveDownloadByRangeDataID(SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequest request) {
            return base.Channel.RetrieveDownloadByRangeDataID(request);
        }
        
        public SimDms.Common.DcsWs.ArrayOfString RetrieveDownloadByRangeDataID(string DataID, long fromID, long toID) {
            SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequest inValue = new SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDRequestBody();
            inValue.Body.DataID = DataID;
            inValue.Body.fromID = fromID;
            inValue.Body.toID = toID;
            SimDms.Common.DcsWs.RetrieveDownloadByRangeDataIDResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveDownloadByRangeDataID(inValue);
            return retVal.Body.RetrieveDownloadByRangeDataIDResult;
        }
        
        public bool IsValid() {
            return base.Channel.IsValid();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimDms.Common.DcsWs.RetrieveDcsDownloadFileResponse SimDms.Common.DcsWs.DcsWsSoap.RetrieveDcsDownloadFile(SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequest request) {
            return base.Channel.RetrieveDcsDownloadFile(request);
        }
        
        public SimDms.Common.DcsWs.DcsDownloadFile[] RetrieveDcsDownloadFile(string DataID, System.DateTime FromDate, System.DateTime ToDate) {
            SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequest inValue = new SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequest();
            inValue.Body = new SimDms.Common.DcsWs.RetrieveDcsDownloadFileRequestBody();
            inValue.Body.DataID = DataID;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            SimDms.Common.DcsWs.RetrieveDcsDownloadFileResponse retVal = ((SimDms.Common.DcsWs.DcsWsSoap)(this)).RetrieveDcsDownloadFile(inValue);
            return retVal.Body.RetrieveDcsDownloadFileResult;
        }
    }
}
